### ISSUE TITLE
Can't start killed process 

### ISSUE THREAD

**Issue by Hukuta** [kevinconway/daemons#12] opened 2014-09-14 11:39 UTC
When I killed daemon process "python ShowMe.py" from OS, 
I am triyng to start it again 

> python ShowMe.py start

and getting error 

> daemon.pid already exist. Cannot start daemon.

but process is dead!

so, I changed in start method

``` python
if pid is not None:
    message = "Pidfile %s already exist. Cannot start daemon."
```

to

``` python
if pid is not None and psutil.pid_exists(pid):
    message = "Pidfile %s already exist. Cannot start daemon."
```

psutil imported from https://github.com/giampaolo/psutil

**Comment by tenortim** [comment] 2016-12-22 01:48
The problem isn't just if the daemon is killed. The same issue happens if it dies unexpectedly. Or the host system crashes or loses power. Or any number of other possibilities. That is why full pidfile handling needs to test that the pid is valid.

I need to test portability of the method, but on POSIX systems, there is no need for external dependencies. It's as easy as something like
```
try:
    os.kill(pid, 0)
except OSError as e:
    if e.errno == errno.EPERM:
        print("pid %d is running under a different username" % pid)
    elif e.errno != errno.ESRCH:
        print("kill of pid %d failed with error %s" % (pid, e.strerror))
    else:
        print("pid %d is running" % pid)
```

Windows supports os.kill in 2.7 onwards. I'll see if it works there.

**Comment by tenortim** [comment] 2016-12-22 22:55
The code as it stands doesn't work on Windows for a number of unrelated reasons.
The signal handling needs SIGQUIT removed since it doesn't exist on Windows (trivial), but then daemonize fails because os.fork doesn't exist either.

As such, I already have a fix (plus tests) for the pidfile handling in my clone. I'll submit a pull request.

**Comment by kevinconway** [comment] 2017-01-05 01:38
Thanks to @tenortim I can finally close this bug!

**Closed by kevinconway** 2017-01-05 01:38 UTC
